### ISSUE TITLE
[Feature Request] ability to change chat nickname

### ISSUE THREAD

**Issue by ForestedDev** [TheFurryDevil-zz/HasiBoundLite#3]
if it is possible, can you add the ability to change the player name that is displayed in chat?

**Comment by ForestedDev** [comment]
if it is possible, could you also add a function to see if the player is typing, one to return what is in the player's text box, and one to change the format used for talking in chat, for example taking \
\<Playername> and making it |Playername|

**Comment by ForestedDev** [comment]
and possibly the ability to prevent the dll from saving your name if you set it when you use star.player.setName(name)

**Comment by SlipyB** [comment]
you can already basically do all of that in the lua

**Comment by ghost** [comment]
To prevent the name save just pit a name xhange in the uninit to what you want it to remain as

**Comment by ForestedDev** [comment]
> you can already basically do all of that in the lua

then how do i change the format used for talking in chat, for example taking
<Playername> and making it |Playername|

**Comment by ForestedDev** [comment]
> To prevent the name save just pit a name xhange in the uninit to what you want it to remain as

tried uninit, no dice
